# Numpy Library

In [5]:
#Library Installation
!pip install numpy

In [8]:
# Importing Library
# Import numpy with alias:
import numpy as np

## 1. Array Creation

In [115]:
# 1 Dimensional Array
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [48]:
arr1.shape

(3,)

In [50]:
# Multidimensional Array
arr2=np.array([
    [[1,2,3],[4,5,6]],
    [[1,5,6],[2,3,7]],
    [[7,8,9],[9,8,6]],
    [[1,0,0],[2,4,0]]
])
arr2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 5, 6],
        [2, 3, 7]],

       [[7, 8, 9],
        [9, 8, 6]],

       [[1, 0, 0],
        [2, 4, 0]]])

In [52]:
arr2.shape

(4, 2, 3)

## 2. Array Creation(Built-in-Methods)

In [66]:
# Array of all zeros
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
# Array of all ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
# Sequence of numbers
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
# Evenly spaced numbers
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [101]:
# Identity Matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [111]:
# Random Values in[0,1]
np.random.rand(4,3)

array([[0.63890744, 0.29846274, 0.95585516],
       [0.66375691, 0.51572643, 0.31637893],
       [0.31748792, 0.0851742 , 0.92062777],
       [0.30341839, 0.71529134, 0.47685843]])

## 3. Array Operations and Functions

In [140]:
# create two arrays
a=np.array([1,2,4])
b=np.array([4,5,6])

#### Arithmet Operations

In [142]:
print("addition",a+b)
print("Subtraction",b-a)
print("Multiplication",a*b)
print("Division",a/b)

addition [ 5  7 10]
Subtraction [3 3 2]
Multiplication [ 4 10 24]
Division [0.25       0.4        0.66666667]


In [149]:
array1=np.array([[1,2,3],[4,5,6]])

#### Aggregate Functions

In [158]:
print(array1.sum())
print(array1.mean())
print(array1.max())
print(array1.min())

21
3.5
6
1


In [211]:
array2=np.array([1,4,9,16])
array2

array([ 1,  4,  9, 16])

#### Mathematical Functions

In [180]:
np.sqrt(array2)

array([1., 2., 3., 4.])

In [182]:
np.exp(array2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [184]:
np.log(array2)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [214]:
array3=np.array([[1,2],[3,4],[5,6]])
array3

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Reshaping Arrays

In [209]:
array3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
array3.flatten()

array([1, 2, 3, 4, 5, 6])

In [219]:
array3.ravel()

array([1, 2, 3, 4, 5, 6])

## 4. Matrix Operations

In [224]:
x=np.array([[1,2],[4,5]])
y=np.array([[5,6],[7,8]])

In [226]:
#Dot Product
np.dot(x,y)

array([[19, 22],
       [55, 64]])

In [228]:
# Transpose
a=np.array([[1,2],[3,4]])
Transpose=a.T
print(Transpose)

[[1 3]
 [2 4]]


## 5. Indexing

In [233]:
import numpy as np
a=np.array([[10,20],
              [30,40]])
print(a[0][1])    
print(a[0,1])    

20
20


In [235]:
# Boolean Indexing
a=np.array([1,4,7,9])
print(a[a>5])  

[7 9]


## 6. Slicing

In [241]:

arr=np.array([10,20,30,40,50])
print(a[1:4])    
print(a[:3])     
print(a[2:])     

[4 7 9]
[1 4 7]
[7 9]


In [245]:
ar=np.array([[ 1,2,3],
              [ 4,5,6],
              [ 7,8,9]])
print(ar[0:2, 0:2])

[[1 2]
 [4 5]]


In [249]:
print(ar[-1])
print(ar[:,-1])     
print(ar[-2:,-2:])  

[7 8 9]
[3 6 9]
[[5 6]
 [8 9]]
